### ISSUE TITLE
Support for Angular 7?

### ISSUE THREAD

**Issue by Epono** [gdi2290/angular-hmr#81]
Hi,

I'm using Angular 7 and I followed [these instructions](https://github.com/angular/angular-cli/wiki/stories-configure-hmr), but states are not saved.
Does it support Angular 7 yet? Is there something missing from the documentation? Or am I just a little stupid and did I miss something?

Also, [this comment](https://theinfogrid.com/tech/developers/angular/enabling-hot-module-replacement-angular-6/#comment-2819) suggests that it won't save state for the modified component, only states of other components, is that what is happening?

Thanks for your help!

**Comment by bufke** [comment]
Actually I got it working. Just ignore the angular cli instructions. The only thing to take from that is using an environment to enable/disable hmr. Here's the relevant lines from my main.ts

```
const bootstrap = () => platformBrowserDynamic().bootstrapModule(AppModule);

if (environment.hmr) {
  if (module[ 'hot' ]) {
    bootstrap().then((ngModuleRef) => {
      return hmrModule(ngModuleRef, module);
    }).catch(err => console.log(err));
  } else {
    console.error('HMR is not enabled for webpack-dev-server!');
    console.log('Are you using the --hmr flag for ng serve?');
  }
} else {
  bootstrap().catch(err => console.log(err));
}
```

Otherwise follow the instructions in this repo's readme. This is tested with angular 7 - so this ticket could probably be closed. Perhaps a section on using with angular cli could be added that warns against using angular-cli's documentation.

**Comment by Epono** [comment]
Never encountered this error :/

Did you follow [these instructions](https://github.com/angular/angular-cli/wiki/stories-configure-hmr) as well? Adding an environment and updating `angular.json`

Also, I run my projet with this command `ng serve --configuration hmr`, I'm not sure what yours does (I'm really no expert in Angular)

**Comment by Epono** [comment]
I created [a small repo](https://github.com/Epono/angular-7-hmr) with a project in which HMR works for Angular 7.
Clone it, `npm i` and `ng serve --configuration hmr`, put some text in the input fields, change something in the code and you should see the changes while keeping what you put in the fields.

**Comment by beelio** [comment]
> I created [a small repo](https://github.com/Epono/angular-7-hmr) with a project in which HMR works for Angular 7.
> Clone it, `npm i` and `ng serve --configuration hmr`, put some text in the input fields, change something in the code and you should see the changes while keeping what you put in the fields.

I tried it out but it does doesn't work for me.

**Comment by Epono** [comment]
That's weird, I just tried it again with Angular 7.1.2 and it worked.  
What's your problem exactly?

**Comment by aymenha** [comment]
@beelio i tried it and it works for me too
what did you try exactly? maybe a fork we can look at?

**Comment by webia1** [comment]
still an issue, see here: https://stackoverflow.com/questions/55355133/angular-7-hmr-hot-module-replacement-does-not-work-if-any-route-resolve-invo
